# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: platform-system
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "-1"
#   finalizers:
#     - resources-finalizer.argoproj.io/finalizer
# spec:
#   description: Controllers and CRDs (Envoy Gateway, future operators)
#   sourceRepos:
#     - https://github.com/simonangel-fong/k8s-multi-cloud.git
#     - registry-1.docker.io/envoyproxy
#   destinations:
#     - server: '*'
#       namespace: '*'
#   clusterResourceWhitelist:
#     - group: '*'
#       kind: '*'
#   namespaceResourceWhitelist:
#     - group: '*'
#       kind: '*'
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: platform-config
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "-1"
#   finalizers:
#     - resources-finalizer.argoproj.io/finalizer
# spec:
#   description: Shared infra config (GatewayClass, Gateway, ClusterIssuer)
#   sourceRepos:
#     - https://github.com/simonangel-fong/k8s-multi-cloud.git
#   destinations:
#     - server: '*'
#       namespace: envoy-gateway-system
#   clusterResourceWhitelist:
#     - group: gateway.networking.k8s.io
#       kind: GatewayClass
#   namespaceResourceWhitelist:
#     - group: '*'
#       kind: '*'
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: tenant-demo
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "-1"
#   finalizers:
#     - resources-finalizer.argoproj.io/finalizer
# spec:
#   description: demo-api tenant workload
#   sourceRepos:
#     - https://github.com/simonangel-fong/k8s-multi-cloud.git
#   destinations:
#     - server: '*'
#       namespace: demo-api
#     - server: '*'
#       namespace: demo-api-*
#   clusterResourceWhitelist: []
#   namespaceResourceWhitelist:
#     - group: '*'
#       kind: '*'
