apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  # generator: select cluster with label
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: demo-api
  template:
    metadata:
      name: '{{ .name }}-01-envoy-gateway'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      finalizers:
        - resources-finalizer.argoproj.io/finalizer
    spec:
      project: default
      revisionHistoryLimit: 3
      # source: helm
      source:
        repoURL: registry-1.docker.io/envoyproxy
        chart: gateway-helm
        targetRevision: v1.8.1
      # destination: selected cluster server
      destination:
        server: '{{ .server }}'
        namespace: envoy-gateway-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m
            factor: 2
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
