apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: envoy-gateway-config
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: demo-api
  template:
    metadata:
      name: '{{ .name }}-02-envoy-gateway-config'
    spec:
      project: default
      source:
        repoURL: https://github.com/simonangel-fong/k8s-multi-cloud.git
        targetRevision: master
        path: argocd/envoy-gateway-config
      destination:
        server: '{{ .server }}'
        namespace: envoy-gateway-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
