apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: envoy-gateway-config
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  # generator: select cluster with label
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: demo-api
  template:
    metadata:
      name: '{{ .name }}-02-envoy-gateway-config'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      finalizers:
        - resources-finalizer.argoproj.io/finalizer
    spec:
      project: default
      revisionHistoryLimit: 3
      # source: manifests
      source:
        repoURL: https://github.com/simonangel-fong/k8s-multi-cloud.git
        targetRevision: master
        path: argocd/envoy-gateway-config
      # destination: selected cluster server
      destination:
        server: '{{ .server }}'
        namespace: envoy-gateway-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m
            factor: 2
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
