apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-api
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: demo-api
  template:
    metadata:
       name: '{{ .name }}-03-demo-api'
    spec:
      project: default
      source:
        repoURL: https://github.com/simonangel-fong/k8s-multi-cloud.git
        targetRevision: master
        path: helm/multicloud-demo-api
        helm:
          valueFiles:
            - 'values-{{ index .metadata.labels "cloud" }}.yaml'
      destination:
        server: '{{ .server }}'
        namespace: demo-api
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
