apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-api
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  # generator: select cluster with label
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: demo-api
  template:
    metadata:
      name: '{{ .name }}-03-demo-api'
      annotations:
        argocd.argoproj.io/sync-wave: "3"
      finalizers:
        - resources-finalizer.argoproj.io/finalizer
    spec:
      project: default
      revisionHistoryLimit: 3
      # source: helm templates
      source:
        repoURL: https://github.com/simonangel-fong/k8s-multi-cloud.git
        targetRevision: master
        path: helm/multicloud-demo-api
        helm:
          valueFiles:
            - 'values-{{ index .metadata.labels "cloud" }}.yaml'
      # destination: selected cluster server
      destination:
        server: '{{ .server }}'
        namespace: demo-api
      ignoreDifferences:
        - group: gateway.networking.k8s.io
          kind: HTTPRoute
          jsonPointers:
            - /spec/rules
            - /spec/parentRefs
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m
            factor: 2
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
