{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "multicloud-demo-api.fullname" . }}
  labels:
    {{- include "multicloud-demo-api.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.gatewayName }}
      namespace: {{ .Values.httpRoute.gatewayNamespace }}
  hostnames:
    - {{ .Values.httpRoute.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.httpRoute.path }}
      backendRefs:
        - name: {{ include "multicloud-demo-api.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
