# values.yaml: aws
env:
  VERSION: "0.1.1"
  CLOUD_PROVIDER: "aws"

httpRoute:
  enabled: true
  gatewayName: eg
  gatewayNamespace: envoy-gateway-system
  hostname: cloud.arguswatcher.net
  path: /api/